name: build

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        ocaml-compiler:
          - "4.13"
          - "4.14"
          - "5.0"
          - "5.1"
          - "5.2"
        include:
          - os: ubuntu-latest
            ocaml-compiler: "4.08"
          - os: ubuntu-latest
            ocaml-compiler: "4.09"
          - os: ubuntu-latest
            ocaml-compiler: "4.10"
          - os: ubuntu-latest
            ocaml-compiler: "4.11"
          - os: ubuntu-latest
            ocaml-compiler: "4.12"
          - os: windows-latest
            ocaml-compiler: "ocaml-base-compiler.4.14.2,system-msvc"
          - os: windows-latest
            ocaml-compiler: "ocaml-variants.5.2.0+msvc"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: set ocamlversion
        run: echo "ocamlversion=$(opam exec -- ocamlc -version)" >>"$GITHUB_OUTPUT"
        id: conf
        shell: bash

      - run: opam install . --with-test --deps-only

      - run: opam exec -- make test

      - run: OCAMLBUILD=$(pwd)/ocamlbuild.native opam exec -- make -C bootstrap
        shell: bash

      - run: opam exec -- make distclean
      - run: opam exec -- opam pin add -n ocamlbuild .
      - run: opam exec -- opam install -v ocamlbuild
      - run: opam exec -- opam install -v menhir
      - run: opam exec -- make build_examples
      - run: opam exec -- opam install -v camlp4
        if: matrix.ocaml-compiler != 'ocaml-variants.5.2.0+msvc'
      - run: opam exec -- env OCB=ocamlbuild ./test/runtest.sh
        shell: bash
      - run: opam exec -- make test-external
        if: matrix.ocaml-compiler != 'ocaml-variants.5.2.0+msvc'
      - run: opam exec -- opam install -v mtime.1.4.0 # this tests topkg, with stub libraries
      - run: opam exec -- opam install -v inotify.2.3 # this tests oasis, with stub libraries
        if: ${{ ! startsWith(steps.conf.outputs.ocamlversion, '5.') && runner.os != 'Windows' && runner.os != 'macOS' }}
      - run: opam exec -- opam install -v cpuid.0.1.1 # this tests the ocb-stubblr plugin
        if: runner.os != 'Windows'
      - run: opam exec -- opam install -v shcaml.0.2.1 # this tests the cppo plugin
        if: ${{ ! startsWith(steps.conf.outputs.ocamlversion, '5.') && runner.os != 'Windows' && runner.os != 'macOS'}}
      - run: opam exec -- opam install -v tgls.0.8.6
        # this caught an ocamlbuild regression in https://github.com/ocaml/opam-repository/pull/27442
        # (incompatible with OCaml >=5.2 and with Windows)
        if: ${{ ! startsWith(steps.conf.outputs.ocamlversion, '5.') && runner.os != 'Windows'}}
