name: build

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - "4.13"
          - "4.14"
          - "5.0"
          - "5.1"
          - "5.2"
        include:
          - os: ubuntu-latest
            ocaml-compiler: "4.08"
          - os: ubuntu-latest
            ocaml-compiler: "4.09"
          - os: ubuntu-latest
            ocaml-compiler: "4.10"
          - os: ubuntu-latest
            ocaml-compiler: "4.11"
          - os: ubuntu-latest
            ocaml-compiler: "4.12"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global core.ignorecase false

      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3.0.0-beta
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          allow-prerelease-opam: true

      - run: opam install . --with-test --deps-only

      - run: opam exec -- make test

      - run: OCAMLBUILD=$(pwd)/ocamlbuild.native opam exec -- make -C bootstrap
        if: runner.os != 'Windows'

      - run: opam exec -- make distclean
      - run: opam exec -- opam pin add -n ocamlbuild .
      - run: opam exec -- opam install -v ocamlbuild
      - run: opam exec -- opam install -v menhir
      - run: opam exec -- opam install -v camlp4
        if: (! startsWith(matrix.ocaml-compiler, '5.2'))
      - run: opam exec -- make test-external
        if: (! startsWith(matrix.ocaml-compiler, '5.2'))
      - run: opam exec -- opam install -v mtime.1.0.0 # this tests topkg, with stub libraries
      - run: opam exec -- opam install -v inotify.2.3 # this tests oasis, with stub libraries
        if: (! startsWith(matrix.ocaml-compiler, '5')) && runner.os != 'Windows'
      - run: opam exec -- opam install -v cpuid.0.1.1 # this tests the ocb-stubblr plugin
        if: runner.os != 'Windows'
      - run: opam exec -- opam install -v shcaml.0.2.1 # this tests the cppo plugin
        if: (! startsWith(matrix.ocaml-compiler, '5')) && runner.os != 'Windows'
